// Auto-generated scheme list from mihomo parser
// Generated by scripts/generate_schemes.go
#ifndef MIHOMO_SCHEMES_H_INCLUDED
#define MIHOMO_SCHEMES_H_INCLUDED

#include <string>
#include <vector>

namespace mihomo {

    const std::vector<std::string> SUPPORTED_SCHEMES = {
        "hysteria",
        "hysteria2",
        "hy2",
        "tuic",
        "trojan",
        "vless",
        "vmess",
        "ss",
        "ssr",
        "socks",
        "socks5",
        "socks5h",
        "http",
        "https",
        "anytls",
        "mierus"
    };

} // namespace mihomo

#endif // MIHOMO_SCHEMES_H_INCLUDED
