// +build ignore

// This script auto-generates mihomo_schemes.h by analyzing the mihomo source code.
// It extracts all supported URI schemes from mihomo's constant/proxy.go or similar files.
//
// Usage: go run scripts/generate_schemes.go

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	// Find mihomo module path
	cmd := exec.Command("go", "env", "GOMODCACHE")
	output, err := cmd.Output()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding GOMODCACHE: %v\n", err)
		os.Exit(1)
	}
	modCache := strings.TrimSpace(string(output))

	// Try to find mihomo in go.mod
	goModBytes, err := os.ReadFile("bridge/go.mod")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading go.mod: %v\n", err)
		os.Exit(1)
	}

	var mihomoPath string
	for _, line := range strings.Split(string(goModBytes), "\n") {
		line = strings.TrimSpace(line)
		if strings.Contains(line, "metacubex/mihomo") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				modulePath := parts[0]
				version := parts[1]
				mihomoPath = filepath.Join(modCache, modulePath+"@"+version)
				break
			}
		}
	}

	if mihomoPath == "" {
		fmt.Fprintf(os.Stderr, "Could not find mihomo module in go.mod\n")
		os.Exit(1)
	}

	fmt.Printf("Analyzing mihomo source at: %s\n", mihomoPath)

	// Walk through mihomo source to find proxy type registrations
	schemes := make(map[string]bool)

	filepath.Walk(mihomoPath, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}

		// Skip test files
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}

		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil
		}

		// Look for scheme registrations
		// Common patterns:
		// - "vmess://" in string literals
		// - constant.Scheme or similar constants
		ast.Inspect(f, func(n ast.Node) bool {
			switch x := n.(type) {
			case *ast.CallExpr:
				// Look for function calls like RegisterScheme or similar
				if sel, ok := x.Fun.(*ast.SelectorExpr); ok {
					if sel.Sel.Name == "Register" || sel.Sel.Name == "register" ||
						sel.Sel.Name == "Add" || sel.Sel.Name == "add" {
						if len(x.Args) > 0 {
							if lit, ok := x.Args[0].(*ast.BasicLit); ok {
								val := strings.Trim(lit.Value, "\"`")
								if strings.HasSuffix(val, "://") {
									scheme := strings.TrimSuffix(val, "://")
									if !strings.Contains(scheme, "\\") {
										schemes[scheme] = true
									}
								}
							}
						}
					}
				}
			case *ast.BasicLit:
				if x.Kind == token.STRING {
					val := strings.Trim(x.Value, "\"`")
					// Pattern: "scheme://" in const definitions or string assignments
					if strings.HasSuffix(val, "://") {
						scheme := strings.TrimSuffix(val, "://")
						if !strings.Contains(scheme, "\\") && !strings.Contains(scheme, " ") {
							// Only consider if it looks like a proxy scheme
							if isProxyScheme(scheme) {
								schemes[scheme] = true
							}
						}
					}
				}
			}
			return true
		})

		return nil
	})

	// Add known schemes
	knownSchemes := []string{
		"hysteria", "hysteria2", "hy2", "tuic", "trojan",
		"vless", "vmess", "ss", "ssr",
		"socks", "socks5", "socks5h",
		"http", "https", "anytls", "mierus",
	}
	for _, s := range knownSchemes {
		schemes[s] = true
	}

	// Sort schemes
	var sortedSchemes []string
	for s := range schemes {
		sortedSchemes = append(sortedSchemes, s)
	}
	sort.Strings(sortedSchemes)

	// Generate header
	var sb strings.Builder
	sb.WriteString("// Auto-generated scheme list from mihomo parser\n")
	sb.WriteString(fmt.Sprintf("// Generated by %s\n", filepath.Base(os.Args[0])))
	sb.WriteString("#ifndef MIHOMO_SCHEMES_H_INCLUDED\n")
	sb.WriteString("#define MIHOMO_SCHEMES_H_INCLUDED\n\n")
	sb.WriteString("#include <string>\n")
	sb.WriteString("#include <vector>\n\n")
	sb.WriteString("namespace mihomo {\n\n")
	sb.WriteString("    const std::vector<std::string> SUPPORTED_SCHEMES = {\n")
	for _, s := range sortedSchemes {
		sb.WriteString(fmt.Sprintf("        \"%s\",\n", s))
	}
	sb.WriteString("    };\n\n")
	sb.WriteString("} // namespace mihomo\n\n")
	sb.WriteString("#endif // MIHOMO_SCHEMES_H_INCLUDED\n")

	outputPath := "src/parser/mihomo_schemes.h"
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outputPath, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s with %d schemes\n", outputPath, len(sortedSchemes))
}

func isProxyScheme(scheme string) bool {
	// Filter out non-proxy schemes
	nonProxy := map[string]bool{
		"http": false, "https": false, // These CAN be proxy schemes
	}
	if _, ok := nonProxy[scheme]; ok {
		return true
	}

	// Proxy schemes typically have certain characteristics
	knownPrefixes := []string{"ss", "vmess", "trojan", "hysteria", "tuic", "vless", "socks", "anytls", "mierus"}
	for _, prefix := range knownPrefixes {
		if strings.HasPrefix(scheme, prefix) {
			return true
		}
	}

	// Also check if it's a well-known proxy scheme
	wellKnown := map[string]bool{
		"hysteria": true, "hysteria2": true, "hy2": true,
		"tuic": true, "trojan": true,
		"vless": true, "vmess": true,
		"ss": true, "ssr": true,
		"socks": true, "socks5": true, "socks5h": true,
		"http": true, "https": true,
		"anytls": true, "mierus": true,
	}
	return wellKnown[scheme]
}
